### ISSUE TITLE
Incorrect Icon Types for Activities, Sea Surface, Land Unit

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#104]
I don't know if this is a global problem, or a problem with just these particular symbol sets but the icon types for all the Activities, Sea Surface icons were missing/incorrect when I tested:

https://github.com/Esri/joint-military-symbology-xml/blob/master/instance/jmsml_D_Activity.xml 
https://github.com/Esri/joint-military-symbology-xml/blob/master/instance/jmsml_D_Sea_Surface.xml

Should be almost all "FULL_OCTAGON" but none were.

**Comment by abouffard** [comment]
Completed and merged in PR #169.  All icon types reviewed and updated where mistakes were found.  This can now be closed at your discretion.

**Comment by csmoore** [comment]
Just a gentle reminder, if you are managing this repo like the other solutions repos, don't forget to assign the issue to the originator to verify (and label/comment "to verify")
