### ISSUE TITLE
Support for Dynamic Symbols

### ISSUE THREAD

**Issue by joebayles** [Esri/joint-military-symbology-xml#119]
I'm sure @abouffard already has a way forward, but I don't know how we will implement dynamic symbols like Atmospheric/Wind/Wind Plot (45140200).

@abouffard @jrweakland we need to ensure that we capture all use cases for dynamic symbology here.

Creating issues for each of the sub-sets of this problem:
- [ ] https://github.com/Esri/joint-military-symbology-xml/issues/182 - Wind Plotting
- [ ]  - Circular Targets

**Comment by abouffard** [comment]
Deferring this issue on the basis that DISA (SSMC) is without 2525 administrative support, and it is unclear when that support will be available.  That support would be needed to create the constituent svg files needed to build dynamic symbols.

**Comment by abouffard** [comment]
We'll review.

**Comment by joebayles** [comment]
@abouffard what's the status of this CP?

**Comment by joebayles** [comment]
@mepler can you weigh in on this?

**Comment by joebayles** [comment]
https://github.com/OGCMetOceanDWG/WorldWeatherSymbols

Now... targets.

**Comment by joebayles** [comment]
Circular targets are derived from attributes, and weather symbols are captured in another issue.

Closing.
