### ISSUE TITLE
Add legacy/conversion support for older versions of 2525 and APP-6

### ISSUE THREAD

**Issue by abouffard** [Esri/joint-military-symbology-xml#131]
We've had a recent user community request for enhancing JMSML to support 2525B Change 2.  So I've created this issue to help track/discuss that enhancement.  It is certainly something we have talked about, something to be done sometime after the initial release is complete.

UPDATE based on coversation w/ @joebayles
 - [ ] Assess SIDC code differences between MIL-STD-2525C and MIL-STD-2525B C2 (like the D/C spreadsheet created by @mepler).
 - [ ] Add legacy codes to XML instances (and possibly adjust the schema to accomodate additional legacy codes).
 - [ ] Incorporate MIL-STD-2525B C2 into the output (readable by the companion application).

**Comment by joebayles** [comment]
Low Priority... they should look to update their systems.

**Comment by conklinbd** [comment]
Disagree. This is a high priority for interoperability with older systems. Many systems will send messages with 2525B Change 2 Symbol ID codes and users would expect to be able to see that data.

**Comment by wmcgrane** [comment]
Gentlemen:
Questions from a DISA perspective:

Is there still disagreement with Mr. Bayles' comment that this is a low priority, given the results of the change proposals to which he refers in a separate posting?  
Is Mr. Bayles priority level designation is from an Esri perspective?
Is Mr. Conklin's disagreement from a COCOM and/ or Program perspective?

Regards,

Bill McGrane
Chair, Symbology Standards Management Committee
DISA EE212
Messaging Standards Section
Ft. Meade, MD
301-225-7383





-----Original Message-----

**Comment by joebayles** [comment]
@wmcgrane,
  This was a discussion of _relative_ vs. _absolute_ priority (the scope of ESRI work backlog vs. necessity from a COCOM/program perspective. We still intend on providing backwards compatibility to MIL-STD-2525B Ch. 2, and have change the priority from low to high. We plan on beginning work on that _relatively_ soon.

**Comment by joebayles** [comment]
Per discussion w/ @abouffard, I've added the list of things to accomplish in the original issue.

**Comment by csmoore** [comment]
Creating a separate issue for APP-6(B) support to separate that out.

(also removing the high priority label from this one - since it doesn't seem like it was a high priority)

**Comment by joebayles** [comment]
Verified.
