### ISSUE TITLE
Produce LegacyMappingTableDtoC Table

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#133]
CSM Updated 6/30/15:

The task in to add the unmapped 2525D->C entities to [LegacyMappingTable](https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/legacy_support/LegacyMappingTableCtoD.csv) so this table looks similar to the previous manually maintained table "2525C and D comparision.xls" so we have all the needed D and C mapping data in one place.

(i.e. add those unmapped entries from https://gist.github.com/csmoore/9b53c4264709a1b9fa47 to the LegacyMappingTable)

~~In the Legacy Samples output: https://github.com/Esri/joint-military-symbology-xml/tree/master/samples/legacy_support~~

~~It does not have the entries/row for the symbols new to 2525D.~~

~~This is also information we would like to also be included (able to see at a glance) - what symbols are new to 2525D (I'm assuming this is the issue since some entries are missing):~~

~~Either:~~
~~1. Add a have a D-to-C table (since this would be a good additional check/test) -or-~~
~~2. Add the missing, new 2525D entries to the existing table (and their mappings if they exist)~~

~~Note: it appears there are some mappings missing since for example: 25140604 : "Direction of Attack : Friendly Planned or On Order" should actually have a 2525C mapping and be included.~~

**Comment by joebayles** [comment]
@abouffard will add the .csv to the JMSML, and link it here.

**Comment by csmoore** [comment]
Would it be possible to reopen this issue - getting a current/definitive list of 2525D->C mapped symbols from this repo is becoming an issue: https://github.com/Esri/joint-military-symbology-xml/issues/124#issuecomment-116699643

**Comment by jrweakland** [comment]
Reopened @csmoore request.

**Comment by csmoore** [comment]
Thanks for reopening -  just to sum up/clarify the issue - the task in to add the unmapped 2525D entities to [LegacyMappingTable](https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/legacy_support/LegacyMappingTableCtoD.csv) so this table looks similar to the previous manually maintained table "2525C and D comparision.xls" & we have all the D and C data in one place.

(i.e. add those unmapped entries from https://gist.github.com/csmoore/9b53c4264709a1b9fa47 to the LegacyMappingTable)

**Comment by joebayles** [comment]
@csmoore did you do this?

**Comment by csmoore** [comment]
@joebayles - no - it is assigned to @abouffard 

There was something similar, an [icon mapping table](https://github.com/Esri/joint-military-symbology-xml/blob/dev/samples/legacy_support/All_ID_Mapping_Original.csv) produced for our project but this specific  issue/request is for something different that can be used for a D to C symbol->mapping tool  (that also has recommended mappings to at least the symbolset so they don't show up as "unknown/retired")

**Comment by Dbarnes1** [comment]
this is the legacy mapping table we need? Perhaps we should close this out if so: https://github.com/Esri/joint-military-symbology-xml/blob/dev/samples/legacy_support/LegacyMappingTableCtoD.csv

**Comment by csmoore** [comment]
That was C -> D - was looking for D -> C - but it is fine to close - I believe we mainly have what we wanted with the icon mapping tables that go from D->C

I think I was mainly looking to be able to auto-generate that manually-maintained mapping spreadsheet.

But more generally these C <-> D Mapping tables concretely captured the interoperability & mapping scenarios:

1. Do C&D systems interoperate? 
2. Do you convert data from C to D (upgrade)? D to C (downgrade)?
3. What happens if I send/convert a C symbol that was retired to D
4. What happens if I send/convert a new D symbol to C
5. and so forth

Having a vetted (i.e. one the community agreed on) & bidirectional mapping table would help greatly in these scenarios, but if 1) from above will/can never happen and you aren't creating tools that convert from D->C, then it won't be needed.

**Comment by Dbarnes1** [comment]
@csmoore thanks for the explanation and sorry for commenting on an issue that's been lingering for years. closing out.

**Comment by csmoore** [comment]
@Dbarnes1 - I went through [any issues I created](https://github.com/Esri/joint-military-symbology-xml/issues/created_by/csmoore) & closed out any I thought were no longer valid
