### ISSUE TITLE
Add vertical bounding octagon

### ISSUE THREAD

**Issue by kjellmf** [Esri/joint-military-symbology-xml#155]
In commit e1fe5c40bafd7d472ff41f0ca84ebe9ea5a12f29 you added the bounding octagon graphic, for reference and testing. It could be useful to also have av vertical version of the octagon as well

![image](https://cloud.githubusercontent.com/assets/29217/5303731/4ba3b5f8-7bec-11e4-9836-b9b8fa525959.png)

My suggestion is to have three different octagon graphics:

- `BoundingOctagon.svg` (with no mod1 and mod2 indicators)
- `BoundingOctagonHorizontal.svg`
- `BoundingOctagonVertical.svg`

If you want I can create the files and submit a pull request.

**Comment by abouffard** [comment]
Added vertical bounding octagon and changed the name of the horizontal bounding octagon in merge #162.

**Comment by kjellmf** [comment]
Thanks @abouffard.

**Comment by abouffard** [comment]
I'm waiting on DISA to send me their octagon svg without the sector lines, then I'll add it too.

**Comment by kjellmf** [comment]
I'm sorry for closing the issue prematurely. For my [symbology explorer](http://kjellmf.github.io/military-symbology-explorer/) I created an "unofficial" bounding octagon manually: [BoundingOctagon.svg](https://github.com/kjellmf/military-symbology-explorer/blob/master/assets/img/BoundingOctagon.svg). Feel free to use it if you don't hear back from DISA.

**Comment by abouffard** [comment]
Thanks @kjellmf

**Comment by joebayles** [comment]
@kjellmf , this symbology explorer is AWESOME! Very cool. I'm adding a link to it on the main repo readme, let me know if that's not OK.

**Comment by conklinbd** [comment]
Yes very nice :+1: @kjellmf

**Comment by kjellmf** [comment]
Thanks @joebayles. Feel free to add a link.

**Comment by csmoore** [comment]
That web app is extremely nice and thorough - a great tool/supplement to the standard - especially thanks for the technical description http://kjellmf.github.io/military-symbology-explorer/#/about and the more succinct JSON format

This is yet another great example of how opening/apache-licensing technical data (in this case data model + images) only benefits the community and ensures overall better quality, tools, collaboration, and more.

**Comment by kjellmf** [comment]
Thank you @csmoore and everyone else for the feedback, and thanks for making the data available to everyone!. I'm glad that you liked the web app. It is a fun project to work on and I will try to make it more user friendly and useful.

**Comment by abouffard** [comment]
Sectorless bounding octagon added in PR #169.

**Comment by kjellmf** [comment]
Excellent. Closing this issue now that all the octagons have been added.
