### ISSUE TITLE
SigInt symbol set modifier folder name should be lowercase

### ISSUE THREAD

**Issue by kjellmf** [Esri/joint-military-symbology-xml#156]
The [SigInt symbol set](https://github.com/Esri/joint-military-symbology-xml/tree/master/svg/MIL_STD_2525D_Symbols/Appendices/SigInt) is the only symbol set that has a [mixed case modifier folder name](https://github.com/Esri/joint-military-symbology-xml/tree/master/svg/MIL_STD_2525D_Symbols/Appendices/SigInt/Mod1)(`Mod1`). This is not reflected in [jmsml.config](https://github.com/Esri/joint-military-symbology-xml/blob/master/source/JointMilitarySymbologyLibraryCS/jmsml.config#L31)(`mod1`). This causes problems on linux systems where file and folder names are case sensitive. I ran into this issue while working on my [symbol browser/explorer](https://github.com/kjellmf/military-symbology-explorer). I use `jmsml.config` to find the SVG folder names and on a linux system this will result in an error when trying to load the sigint modifiers. 

A quick fix is to rename the folder from `Mod1` to `mod1`.

**Comment by abouffard** [comment]
Thanks for the comment, kjellmf.  Easily fixed.

**Comment by abouffard** [comment]
Fixed in #159
