### ISSUE TITLE
How can we find the frame of a cyberspace symbol from the symbol identification code?

### ISSUE THREAD

**Issue by kjellmf** [Esri/joint-military-symbology-xml#157]
Does anyone know how to figure out the correct frame for a symbol in the cyberspace symbol set from the symbol identification code?  According to the 2525D-spec we should pick a standard identity and dimension when drawing a cyberspace symbol. The symbol below is for instance a friendly air webserver.

![image](https://cloud.githubusercontent.com/assets/29217/5710600/d7f5bfee-9aa3-11e4-8e2a-64382bcc553e.png)
 
In the JMSML schema the dimension is an attribute of the symbol set. The value for the cyberspace symbol set is `DimensionID="AIR SPACE LAND_EQUIPMENT SEA_SURFACE SEA_SUBSURFACE"`. The symbol identification code does not have a dimension field, so the `DimensionID` does not give us enough information to pick a frame. 

Any thoughts on this problem?

**Comment by abouffard** [comment]
That's a known limitation/mistake in 2525D and APP-6(C) Annex A.  The Cyberspace symbol set code (60) should have been broken down into a range of values like was done with SIGINT.  So at the moment, there is no way to determine frame shape based solely on SIDC.  The current plan is to begin work on 2525D Change 1 and APP-6(D) simultaneously, make them the same fundamental standard, and in them change the single code (60) to a range of codes (60, 61, 62, 63, and 64).

**Comment by kjellmf** [comment]
Thanks @abouffard for the explanation.

**Comment by csmoore** [comment]
@abouffard - Just checking back to see if this issue of clarifying the cyberspace frame was ever turned into a CP or addressed (another option could be to simply pick a frame for this symbolset like  the equipment frame/circle)

**Comment by abouffard** [comment]
@csmoore, the CP for this is being authored this week and will be discussed and voted on in two weeks at the next SSMC/JSP meeting.
