### ISSUE TITLE
Wrong Shape for some Affiliations?

### ISSUE THREAD

**Issue by JKCowboy** [Esri/joint-military-symbology-xml#164]
It appears the frame shapes for REALITY_LU_FRIEND, EXERCISE_LU_FRIEND. and SIMULATED_LU_FRIEND are not correct (they show CIRCLE for the shape). The MIL Standard 2525D show these should be rectangles for units (TABLE I-III, Pages 12-14).

The XML in jmsml_D_Base.xml

<Affiliation ID="REALITY_LU_FRIEND" ContextID="REALITY" DimensionID="LAND_UNIT" StandardIdentityID="SI_FRIEND" Shape="CIRCLE" Graphic="0_310_0.svg" PlannedGraphic="0_310_1.svg" CivilianGraphic="0_310_0c.svg" PlannedCivilianGraphic="0_310_1c.svg">
      <LegacyStandardIdentityCode Name="2525C" FirstFunctionLetter="U">F</LegacyStandardIdentityCode>
    </Affiliation>

    <Affiliation ID="EXERCISE_LU_FRIEND" ContextID="EXERCISE" DimensionID="LAND_UNIT" StandardIdentityID="SI_FRIEND" Shape="CIRCLE" Graphic="1_310_0.svg" PlannedGraphic="1_310_1.svg" CivilianGraphic="1_310_0c.svg" PlannedCivilianGraphic="1_310_1c.svg">
      <LegacyStandardIdentityCode Name="2525C" FirstFunctionLetter="U">D</LegacyStandardIdentityCode>
    </Affiliation>

    <Affiliation ID="SIMULATED_LU_FRIEND" ContextID="SIMULATION" DimensionID="LAND_UNIT" StandardIdentityID="SI_FRIEND" Shape="CIRCLE" Graphic="2_310_0.svg" PlannedGraphic="2_310_1.svg" CivilianGraphic="2_310_0c.svg" PlannedCivilianGraphic="2_310_1c.svg"/>

**Comment by abouffard** [comment]
Thanks for the feedback.  I'll take a look.

**Comment by abouffard** [comment]
Fixed in #165
