### ISSUE TITLE
Update SVG Known Issues (and add SVG file/id column)

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#175]
I noticed these show up in the [KNOWN_ISSUES table](https://github.com/Esri/joint-military-symbology-xml/blob/master/svg/KNOWN_ISSUES.md) but look fixed:

http://kjellmf.github.io/military-symbology-explorer/#/explore/10041010111213030000
http://kjellmf.github.io/military-symbology-explorer/#/explore/10061010111213030000
http://kjellmf.github.io/military-symbology-explorer/#/explore/10041000001204020000 
http://kjellmf.github.io/military-symbology-explorer/#/explore/10061000001204020000 

When you are updating this table, can you add a column with the filename or ID (even better link to SVG) that has the issue.

(I didn't want to update the table myself in case it wasn't the correct issue/svg/ID):

**Comment by abouffard** [comment]
Thanks for the reminder.  Those have all been fixed.

**Comment by csmoore** [comment]
Good deal - if those issues from that current table have all been addressed, then the only remaining known svg issue that comes to mind for me is the issue with the different/various reference sizes used for the control measure and weather points - is that issue being tracked somewhere in this repo (I remember discussing at length, just not sure where it is being tracked)?

Ex:

Small:
http://kjellmf.github.io/military-symbology-explorer/#/explore/10012500003217050000

Medium:
http://kjellmf.github.io/military-symbology-explorer/#/explore/10012500001808000000

Large:
http://kjellmf.github.io/military-symbology-explorer/#/explore/10012500002108000000
http://kjellmf.github.io/military-symbology-explorer/#/explore/10014500001902100000

**Comment by abouffard** [comment]
Nope, its is not currently being tracked.  I'll write a CP this week to have those size differences fixed/addressed and submit it to DISA and we'll track it that way.  

DISA will review it, as will the Service reps, and if they feel for some reason those sizes are appropriate, they'll let us know.  Otherwise, they'll know to fix them for Change 1.

I'll also add it to the svg issue doc when I update it to close those open statuses.

**Comment by abouffard** [comment]
[CP 031815-1](https://github.com/Esri/joint-military-symbology-xml/blob/master/documentation/change_proposals/CP_Esri_150318-1.doc) has been authored and submitted to cover these size issues and was Deferred by the SSMC at the SSMC/JSP 15-1 meeting.  DISA intends to bring this back up at a later date (the next meeting) after they have a chance to review the svg files and have their contract support back online.

**Comment by joebayles** [comment]
Since this issue has been rectified (CP created and submitted), we can just track the CP.
