### ISSUE TITLE
Add Simple High Level Schema Description/Doc

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#19]
It looks like this has already been thought of: Missing Sections here:  https://github.com/Esri/joint-military-symbology-xml/blob/master/documentation/APIUserDoc.md#schema-reference

So just wanted to add an issue to remind/track. Given that this repo is now at the maturing/stabilizing stage, it is probably time to add those missing sections to the doc (perhaps as separate .md files since that doc is already too large) and produce some high level description, diagrams, that explain the schema to a newcomer.

Something brief, high-level that explains the schema and has a few diagrams - something similar to what you might put in a 10-slide executive briefing or training overview.

**Comment by abouffard** [comment]
Added in #162

**Comment by csmoore** [comment]
This is there - could probably use a link to it from one of the other top level readme/documents so it can be found (like https://github.com/Esri/joint-military-symbology-xml/blob/master/documentation/README.md )
