### ISSUE TITLE
15-036-DS, Allow Unspecified Entities

### ISSUE THREAD

**Issue by abouffard** [Esri/joint-military-symbology-xml#192]
Add a new first row in each of TABLES A-VII, A-XIII, etc. (i.e., all the Appendix A entity/entity type/entity subtype icon-based tactical graphic tables), and make this new first row have its Entity as “Unspecified” and its Code is 000000.  The “Unspecified” Entity and its code 000000 does not apply to any unframed symbology sets.  

Add the following to the Appendix A guidance for Entity/Entity Type/Entity Subtype: “If an entity is “Unspecified”, then the remainder of the second set of ten digits shall be set to 0.”

For example:

Entity | Entity Type | Entity Subtype | Code
----------|----------|----------|----------
Unspecified [Symbol Set name here] | | | 000000
Weapons/Weapons System | | | 110000
 | Rifle | | 110100
 | | Single Shot Rifle | 110101

Remove all occurrences of the string, “This symbol shall not be displayed on a C2 system but may be displayed for training or hierarchical explanation purposes.”

For those entities or entity types that are documented for hierarchical purposes only, we will remove the Type and Icon Type entries and change the “No icon associated..etc” comment to “Reserved for hierarchical purposes.”

**Comment by csmoore** [comment]
Just a question/clarification about the language used in this change, does this mean you *will* or *will not* be able to create symbols like these examples below after this change - having these more general/generic symbols available, that already have icons assigned, would be helpful to an end user (and was my intention in the [original request](https://github.com/Esri/joint-military-symbology-xml/issues/124#issuecomment-72894531) ) :

![image](https://cloud.githubusercontent.com/assets/3090809/8854044/d6cb6104-312b-11e5-90fc-0a7703d0ece4.png)

![image](https://cloud.githubusercontent.com/assets/3090809/8854063/f029bc22-312b-11e5-9198-16b56e8c8cf0.png)

**Comment by JKCowboy** [comment]
We too use these "generic" symbols.

**Comment by joebayles** [comment]
That remark is being struck from 2525D and APP 6. If there is a symbol, it's valid.

**Comment by jrweakland** [comment]
https://app.asana.com/0/22998302507476/43808146567943

**Comment by abouffard** [comment]
To answer your question, @csmoore , this CP still allows for the creation of those symbols, it just removes the remarks that otherwise were restricting users regarding how they used those symbols.

The deletion of the "Type" and "Icon Type" entries mentioned in the CP refers to the standard itself, where entries in the various appendix tables show an N/A symbol, the standard will be amended to remove the Type and Icon Type text from the first column and alter the remark to read "Reserved for hierarchical purposes."

![image](https://cloud.githubusercontent.com/assets/4564846/9123354/8f61485e-3c54-11e5-9168-a488e009805b.png)

**Comment by abouffard** [comment]
Closing because this has now been implemented.
