### ISSUE TITLE
Add missing/retired 2525C symbols to C->D Symbol Mapping Table (Redux)

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#196]
I originally opened this issue as #124, but that issue appears to have been [closed for an unrelated issue](https://github.com/Esri/joint-military-symbology-xml/issues/124#issuecomment-92446172) (& just a process reminder to let the issue originator verify the issue where appropriate/possible).

The original issue is that these valid 2525C symbols are missing from the [LegacyMappingTableCtoD](https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/legacy_support/LegacyMappingTableCtoD.csv) so when a user (in this case me when I was writing the 2525C->D converter tool) doesn't get a 2525D symbol returned for these valid symbol ids.

These missing symbols should be added (presumably as mapping to removed/retired):
- [ ]  1    E-OPBJ--------- Emergency Management Symbols, Operations, Emergency Operation, Emergency Team
- [ ]  2    S-FPAH--------- Special Operations Forces (Sof) Unit, Aviation, Rotary Wing
- [ ]  3    S-GPEVC-------- Equipment, Ground Vehicle, Civilian Vehicle
- [ ]  4    S-GPEWDHS------ Weapon, Direct Fire Gun, Heavy, Self-Propelled
- [ ]  5    S-GPEWDLS------ Weapon, Direct Fire Gun, Light, Self-Propelled
- [ ]  6    S-GPEWDMS------ Weapon, Direct Fire Gun, Medium, Self-Propelled
- [ ]  7    S-GPEWHHS------ Weapon, Howitzer, Heavy, Self-Propelled
- [ ]  8    S-GPEWHLS------ Weapon, Howitzer, Light, Self-Propelled
- [ ]  9    S-GPEWHMS------ Weapon, Howitzer, Medium, Self-Propelled
- [ ]  10   S-GPEWMATE----- Weapon, Missile Launcher, Air Defense (AD), Theater, TELAR
- [ ]  11   S-GPEWMATR----- Weapon, Missile Launcher, Air Defense (AD), Theater, TLAR
- [ ]  12   S-GPI-----H---- Installation
- [ ]  13   S-GPIP----H---- Installation, Processing Facility
- [ ]  14   S-GPIR----H---- Installation, Raw Material Production/Storage
- [ ]  15   S-GPIUED--H---- Installation, Service, Research, Utility Facility, Electric Power Facility, Dam
- [ ]  16   S-GPIUEF--H---- Installation, Service, Research, Utility Facility, Electric Power Facility, Fossil Fuel
- [ ]  17   S-GPIU----H---- Installation, Service, Research, Utility Facility
- [ ]  18   S-GPIUR---H---- Installation, Service/Research/Utility Facility, Technological Research Facility
- [ ]  19   S-GPIUT---H---- Installation, Service/Research/Utility Facility, Telecommunications Facility
- [ ]  20   S-GPUCDC------- Combat, Air Defense, Composite
- [ ]  21   S-GPUCDSS------ Combat, Air Defense, Short Range, Stinger
- [ ]  22   S-GPUCFH------- Combat, Field Artillery, Howitzer/Gun
- [ ]  23   S-GPUCSG------- Combat, Internal Security Forces, Ground
- [ ]  24   S-GPUCSGD------ Combat, Internal Security Forces, Ground, Dismounted
- [ ]  25   S-GPUSS3AC----- Combat Service Support, Supply, Class III, Aviation, Corps
- [ ]  26   S-GPUSS3AT----- Combat Service Support, Supply, Class III, Aviation, Theater
- [ ]  27   S-GPUSXR------- Combat Service Support, Maintenance, Recovery
- [ ]  28   S-GPUSXRC------ Combat Service Support, Maintenance, Recovery, Corps
- [ ]  29   S-GPUSXRT------ Combat Service Support, Maintenance, Recovery, Theater
- [ ]  30   S-GPUUACRS----- Combat Support, Cbrn, Chemical, Recon, Wheeled Armored Vehicle, Surveillance
- [ ]  31   S-GPUUI-------- Combat Support, Information Warfare Unit
- [ ]  32   S-GPUUL-------- Combat Support, Law Enforcement Unit
- [ ]  33   S-GPUUMSEA----- "Combat Support, Military Intelligence. Signal Intelligence (Sigint), Electronic Warfare, 
  Armored Wheeled Vehicle"
- [ ]  34   S-GPUUSCL------ Combat Support. Signal Unit, Communication Configured Package, Large Communication Configured Package (LCCP)
- [ ]  35   S-GPUUSMS------ Combat Support, Signal Unit, Multiple Subscriber Element, Small Extension Node
- [ ]  36   S-GPUUSW------- Combat Support, Signal Unit, Telephone Switch
- [ ]  37   S-SPCH--------- Combatant, Hovercraft
- [ ]  38   S-SPCPSUM------ Combatant, Patrol, Antisurface Warfare, Antiship Missile
- [ ]  39   S-UPSUM-------- UNMANNED UNDERWATER VEHICLE
- [ ]  40   S-UPWMC-------- Subsurface Track, Underwater Weapon, Sea Mine, General Milco
- [ ]  41   S-UPWMFC------- Subsurface Track, Underwater Weapon, Sea Mine, Sea Mine (Floating), Floating Milco
- [ ]  42   S-UPWMGC------- Subsurface Track, Underwater Weapon, Sea Mine, Sea Mine (Ground), Ground (Bottom) Milco
- [ ]  43   S-UPWMMC------- Subsurface Track, Underwater Weapon, Sea Mine, Sea Mine (Moored), Moored Milco
- [ ]  44   S-ZP----------- Unknown, Unknown
- [ ]  45   WOS-HHDMDBP---- Hydrography, Dangers/Hazards, Mine-Naval, Mine-Naval (Doubtful)
- [ ]  46   WOS-HHDMDFP---- Hydrography, Dangers/Hazards, Mine-Naval, Mine-Naval (Definite)

**Comment by wmcgrane** [comment]
Chris Moore:
The information you are looking for is on the second tab of the attached spreadsheet.  The second tab includes a list of symbol codes from 2525C that were removed from 2525D.   For example, a worksheet search of "GPEWDLS" returns several instances in the "Symbols removed" tab (i.e. Column A, Line 60:  Weapon, Direct Fire Gun, Medium, Self-Propelled).

Andy Bouffard:
Does this GitHub site have a list of the removed symbols as well, based on this spreadsheet, or only the list from the first tab "Code matrix"?  If not, I think it would be helpful to implementers.  Maybe that should be added under  the legacy_suppport  tag in this repo.

Comments, anyone?

Bill McGrane
Chair, Symbology Standards Management Committee
DISA EE212
Messaging Standards Section
Ft. Meade, MD
301-225-7383



-----Original Message-----

**Comment by csmoore** [comment]
I guessed these were likely removed/retired, I was mainly just asking that they be added to that table so an implementer would know this. For now I just manually added them to [my version of the table here](https://github.com/csmoore/military-feature-toolbox/blob/v.next/toolboxes/mil2525d/tooldata/LegacyMappingTableCtoD.csv#L1957).

I likely would not of even noticed this, but the small 2525C sample/test dataset I was using happened to have several of these symbols. But I am definitely getting that behavior [mentioned here](https://github.com/Esri/joint-military-symbology-xml/issues/124#issuecomment-72894531) where a good 2525C air defense or artillery symbol is mapping to an "?"/invalid symbol - so hopefully that behavior/workflow can be improved in the future.

**Comment by wmcgrane** [comment]
Chris:
Yes, and that's sort of what I was suggesting:  that the list of removed symbols/id codes be added to the table or added as a separate table for reference. 

Bill McGrane
Chair, Symbology Standards Management Committee
DISA EE212
Messaging Standards Section
Ft. Meade, MD
301-225-7383




-----Original Message-----

**Comment by drdanstephens** [comment]
When this item is completed, will there also be a reason listed for why the missing 2525C SIDCs were not included in 2525D?

**Comment by wmcgrane** [comment]
For discussion at the joint JSP/SSMC meeting next week.

Bill McGrane
Chair, Symbology Standards Management Committee
DISA BDC/EE212
Messaging Standards Section
Ft. Meade, MD
301-225-7383




-----Original Message-----

**Comment by abouffard** [comment]
I will add the DISA spreadsheet to this repo.  I'll also review the above list of SIDCs and determine their current status in the XML and add explanatory notes to the csv output where appropriate.

**Comment by csmoore** [comment]
I'm not sure we should add another, slightly different set/format of information (the DISA spreadsheet) - unless it is for historical purposes.  

If the goal is to get to one, open-format(not .xls), configuration-managed set of this (2525C<->D mapping) information in this repo (that we can then improve upon as needed) - would it be possible to add any additional/missing information from the DISA spreadsheet to this datamodel/table so we get to this one set of 2525C<->D info?  

Just checking that this is the desired end-state here, rather than for the community to continue referencing/maintaining the .xls.

**Comment by csmoore** [comment]
I'm not sure about the status of this issue, but I just updated the list in the original issue after testing against the latest LegacyMappingTableCtoD (a few were able to be removed)

**Comment by abouffard** [comment]
I will review and address this issue as part of the larger effort in working on the C to D lookup.

**Comment by wmcgrane** [comment]
Okay.  By the way, is it "Redland" or "Redlands", CA?

-----Original Message-----

**Comment by joebayles** [comment]
Redlands, plural.

**Comment by joebayles** [comment]
@abouffard can you update this as necessary?

**Comment by csmoore** [comment]
This one looks done - I thought at some point there was agreement to have the "retired" symbols (9810000 ?) at least map to the correct symbol set in the new standard, but that can be a discussion for elsewhere - if these tables get used in a conversion tool.
