### ISSUE TITLE
Typo in domain "Principle Direction of Fire" should be "Principal Direction of Fire"

### ISSUE THREAD

**Issue by abouffard** [Esri/joint-military-symbology-xml#197]
_From @BobBooth on June 3, 2015 19:55_

In Control Measures : Maneuver Lines the domain value is "Principle Direction of Fire" with an "le" - should be "Principal Direction of Fire" with an "al".
@csmoore @abouffard 

_Copied from original issue: Esri/military-features-data#81_

**Comment by abouffard** [comment]
_From @csmoore on June 4, 2015 11:13_

Good catch - this will need fixed in the JMSML source data ( https://github.com/Esri/joint-military-symbology-xml/search?utf8=%E2%9C%93&q=Principle&type=Code ) 

& addressed when the domains are regenerated ( #80 )

**Comment by wmcgrane** [comment]
Just some info supporting Andy's correction:  http://www.diffen.com/difference/Principal_vs_Principle 
Great site, by the way.  Explore some of the other "differences" discussed.   :-)

Bill McGrane
Chair, Symbology Standards Management Committee
DISA EE212
Messaging Standards Section
Ft. Meade, MD
301-225-7383



-----Original Message-----
