### ISSUE TITLE
Mine warfare icons question

### ISSUE THREAD

**Issue by spatialillusions** [Esri/joint-military-symbology-xml#199]
Hi, 

I got a question about the mine warfare icons. I'm building my own implementation of 2525D and I kind of got stuck on the mine warfare icons.
The mine warfare symbols have both a Framed medal icon, and a framed alternative icon, how do you choose what to use?
My first idea was to use the framed medal when you had color, and the framed alternative when you were using monocolor, but that dosen't really make sense. And then we have the problem that the alternative icon has some symbols that the medal icons don't, what should be displayed if I give a symbol code for an alternative icon, but have chosen to display medals icons? 
My guess is that it is some sort of 2525 vs APP6 thought behind this, but would it be right to make the option where I choose if I should use 2525 or APP6 also control what kind of mine symbols I should use, this is my best alternative at the moment, but it doesn't really feels like the right solution. 

Is there anyone who can give me some guidance about this?

**Comment by jrweakland** [comment]
@spatialillusions - @abouffard will be out of the office next week but should be able to provide some guidance once he gets back.

**Comment by spatialillusions** [comment]
Ping, is @abouffard back? Would be nice to get some guidance before I try to make some kind of implementation.

**Comment by joebayles** [comment]
>MIW symbols are represented using Mine Warfare Environmental Decision Aids Library (MEDAL) icons embedded within MIL-STD-2525 standard identity frames. The color in MEDAL icons represents the threat level of that contact. Red denotes mine, orange denotes mine-like contact (MILCO), yellow denotes mine-like echo (MILEC), dark green denotes non-mine mine-like object (or non-mine) and bright green denotes neutralized mine. An alternative icon set directly corresponding to MEDAL icons may also be used. The alternative set depicts the same MEDAL icons, but depicts them as black icons eliminating the color threat coding scheme. The MEDAL icons shall be used with unfilled subsurface frames. The alternative icons shall be used with the normal subsurface frames (see tables F-I, F-II and F-III). Figure F-4 shows examples of framed MEDAL and alternative icons.

@spatialillusions I think you're right that it's basically a question of color vs. monochrome. I think it's understood and accepted that you lose some functionality in your symbols if you choose the alternate vs. MEDAL icons. @abouffard might be able to weigh in more, but really these icons are developed by proponent agencies (in this case, the US Navy). So, bottom line, depending on what you're trying to do, either would work. Sorry if this is nebulous guidance, I hope it helps.

**Comment by wmcgrane** [comment]
Andy is away on holiday.  Not sure when he will be back.   Might ask Joe Bayles (his co-worker) if he knows when Andy will be back.

Bill McGrane

-----Original Message-----

**Comment by joebayles** [comment]
@wmcgrane He's gone for a couple weeks. You could definitely weigh in, but I think my previous post answers the question.

**Comment by spatialillusions** [comment]
Thank you for your replies! I figure out some way to implement it during the next weeks, at the moment I think it will be a per symbol property where you set if you want a medallion or not. It is however very strange that you don't have a medallion _and_ an ordinary icon for all symbols.

**Comment by joebayles** [comment]
Well, they don't mean "medallion" when they say MEDAL, they mean that those color symbols were developed for the **M**ine Warfare **E**nvironmental **D**ecision **A**ids **L**ibrary, which is a US Navy system. It seems like MIL-STD-2525B just had the alternate symbols, MIL-STD-2525C mixed MEDAL and alternate into one, and now MIL-STD-2525D separates them. This is probably why you see a discrepancy between the two. I'm assuming that the alternate symbols were incorporated into the standard because, while the MEDAL is very prevalent in the US Navy, they want to maintain continuity and backwards compatibility.

**For the record, when I say "they", I mean either the NATO Joint Symbology Panel or the DOD Symbology Standards Management Committee, the groups that maintain APP-6 and MIL-STD-2525.*

Of course, all of that is conjecture, and I'd like to hear @wmcgrane or @abouffard weigh in. Glad you figured out how you'd implement it in the meantime.

**Comment by spatialillusions** [comment]
Oh, sorry, of course I meant medal, blaming part autocorrect and part to tired to think. 
It will be a bit tricky for me to implement, since I got some legacy in my library that I will have to consider. The users of my library are mostly using APP6b/2525C, and 2525D is just an option that is used if the use number based SIDC, so I already have an option telling the library if they prefer 2525 or APP6, but all letter based SIDC will return a symbol. Now I will have to do something similar for medal/alternate icons. At the moment I'm struggling if I should do it as a global option, that will make it easy to switch, but I won't be able to display them side by side, or a per symbol setting that gives more flexibility, but will be trickier for users to implement.

The mine warfare symbols has always been a bit trickier to implement than the rest of the symbols, sort of, and this way is definitely better than the old, but I still have to give it some extra thought before I start coding. It's not tricky to implement, I just need to figure out how to make my API as simple as possible to use.

**Comment by abouffard** [comment]
Sorry for the delay in replying.

I'm inquiring with a naval symbology expert friend of mine, but I believe the choice of when to use framed vs. unframed MEDAL icons does come down to user preference and is left to implementers to decide for themselves how each plans to handle it.  

I think the framed versions of the icons were intended to work in systems where everything is framed for simplicity and clarity, and to allow the MEDAL icons to conform to the "everything in a frame" approach to 2525 and APP-6.  I believe the unframed colored versions of the icons are more in line with how some naval systems implement MEDAL now and in the past (the legacy argument).

It's on my list of things to do to add an attribute to JMSML to denote which entities must be framed vs. which must not be framed.

**Comment by spatialillusions** [comment]
Hi, 

Thank you for your reply. I implemented it by adding a property in my API called alternateMedal that you can set to true if you want to use alternate symbols. 
You can find my library here:
https://github.com/spatialillusions/milsymbol
And all documentation here:
http://spatialillusions.com/milsymbol/
(Just released the new version with full support for 2525D icons yesterday.)

Best regards
Måns

**Comment by joebayles** [comment]
From Jake Wetzel, SPAWAR:
... MEDAL should be without ID, just a colored icon. The 2525 symbol is with colored icons (red, orange, yellow, dark green, and light green) with the unfilled symbol affiliation frame (i.e. Red framed hostile, no color fill, with MEDAL-colored icon). The alternative view was black and white icons with the more traditional 2525 symbol. Neither 2525 is really optimal, but the colored icon is paramount to the symbol. That is how it should be depicted. 2525 relies on affiliation, but for weapons like ballistic missiles and mines, affiliations mean little. There, impact means everything. We should have a weapons symbology set that extricates itself from affiliation. I am already thinking of exceptions...

**Comment by jrweakland** [comment]
@spatialillusions - please close this issue when appropriate. thanks.

**Comment by spatialillusions** [comment]
The result of my implementation can be seen here:
http://spatialillusions.com/milsymbol/docs/milsymbol-2525d.html#TABLEA-XXXVII

**Comment by csmoore** [comment]
Nice - that is impressive you were able to implement all those tables from the standard. I also like how the one's with Civilian in the name default to that frame - that's another one of those "optional" properties it is hard to know exactly how one should generally implement.

**Comment by spatialillusions** [comment]
Thanks! :-)

You can find the complete API for milsymbol here:
http://spatialillusions.com/milsymbol/docs/index.html#symboloptions
Civilian colors is by default set to true, but you can disable it if you want to. (There is lots and lots of options that makes it possible for you to adjust basically anything.)
