### ISSUE TITLE
Remove Special Entity Subtypes from Coded_Domain_Land_Unit_Entities

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#201]
These values should be removed from Coded_Domain_Land_Unit_Entities.csv

https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/name_domains_values/Coded_Domain_Land_Unit_Entities.csv#L193

Special Entity Subtypes : Headquarters Element  XXXX95
Special Entity Subtypes : Division and Below Support  XXXX96
Special Entity Subtypes : Corps Support  XXXX97
Special Entity Subtypes : Theater/Echelons Above Corps Support  XXXX98

They cause the domain import to fail (which is expecting an integer for the value field)

**REQUIRED WORKAROUND** If you are importing these domains from this csv, you may need to delete these lines from the csv prior to performing the import - see: https://github.com/Esri/military-features-data/tree/v.next/data/mil2525d/utilities/military-features-utilities#steps

**Comment by abouffard** [comment]
Resolved by #211 

@csmoore , sorry about PR vs issue confusion.  Getting ahead of myself and GitHub has every interface looking the same...

Please verify and close this issue at your convenience,

**Comment by csmoore** [comment]
Verified
