### ISSUE TITLE
"Downed Aircraft Pick-Up Point" should be "Downed Aircrew Pick-Up Point"

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#202]
Symbol={SymbolSet=25, Entity=180300} -  "Downed Aircraft Pick-Up Point" should be "Downed **Aircrew** Pick-Up Point"

https://github.com/Esri/joint-military-symbology-xml/blob/master/instance/jmsml_D_Control_Measure.xml#L905

Noted by @BobBooth here: https://github.com/Esri/military-features-data/issues/39#issuecomment-104379830

**Comment by abouffard** [comment]
I will fix this but realize that there is a misspelling of Point in the standard and will draft a CP to address.

**Comment by abouffard** [comment]
Corrected and now reflected in JMSML at #205

**Comment by abouffard** [comment]
@csmoore , please confirm fix and close.

**Comment by csmoore** [comment]
Verified fixed
