### ISSUE TITLE
Remove "extension" coded values from domain exports

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#203]
I just noticed the multiple "Extension" values are back in the samples/domain values in the latest version of our GDB. 

Please remove from the same exports, ex: https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/symbolcode_firstten_domains_values/jmsml_Amplifier.csv#L11 & https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/symbolcode_firstten_domains_values/jmsml_StandardIdentity.csv#L9 (I realize these are this way in the standard, but not needed in the samples/domains)

Note: this was apparently fixed once in the domains (but perhaps not in the source data?), issue re-opened from/for reference:
https://github.com/ArcGIS/military-features-pro-data_RETIRED_DONT_USE/issues/72 (Note: internal link)

**Comment by abouffard** [comment]
@csmoore please confirm fix and close.

**Comment by csmoore** [comment]
Verified fixed
