### ISSUE TITLE
Special C2 Headquarters Modifier Inconsistency in Standard/Display for Land and Sea Units

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#204]
The Special C2 Headquarter Text Modifier attribute/field "AA" is only shown in 2525D (May 2014) "APPENDIX E/F - SEA (Sub) SURFACE SYMBOLS" Symbol Figure ("FIGURE E-2/F-2")  but is *not* shown in the accompanying table (TABLE E-II/F-II). 

However, this same modifier is *not* shown APPENDIX D - LAND SYMBOLS, in FIGURE D-3 (where it likely should be shown), but it *is* shown in the accompanying table, TABLE D-II.

More importantly, because there is no valid symbol with just a frame and no central icon, there is no way to currently display this "AA" text in the icon center of a valid symbol.

Suggested corrective action is:

1. Add Special C2 Headquarter Field "AA" to FIGURE D-3 
2. Add Special C2 Headquarter Field "AA" to TABLE E-II and Table F-II
3. If not already done, add symbol with just empty frame to symbol sets (Note: 2525C did have a "Special C2 Headquarters" symbol, but [it appears to have been retired at 2525D](https://github.com/Esri/joint-military-symbology-xml/blob/master/instance/jmsml_D_Land_Unit.xml#L3259) )

    a. Note: I see where this Change Request, 15-036-DS, was possibly already approved here https://github.com/Esri/joint-military-symbology-xml/issues/192 , but I don't see any Unspecified/"000000" entries in the repo data

I'm not sure if this modifier/text is used in symbols sets other than land/sea, but I noticed this issue while trying to create a set of symbols similar to: 
![image](https://cloud.githubusercontent.com/assets/3090809/8832546/bc74106c-3077-11e5-856f-ad1ea5b01d91.png)

**Comment by abouffard** [comment]
I will author a CP making sure that the standard is consistent regarding this AA amplifier for 2525D Change 1.

**Comment by joebayles** [comment]
@csmoore @abouffard already brought this to the committee and they are aware. The CP will pass.

**Comment by jrweakland** [comment]
https://app.asana.com/0/22998302507476/43808146567937

**Comment by abouffard** [comment]
CP 15-036-DS has now been implemented in JMSML (#209) and once these changes are reflected in updated domain ranges in military features data feature classes, special C2 HQ symbols can be created.

We are waiting to receive all approved 2525D Change 1 CPs from DISA.  Once received, I will review them to determine if a CP was already approved to add the AA amplifier code to the diagrams and tables in the standard.  That information will then determine what we do next regarding drafting a new CP.

**Comment by abouffard** [comment]
@csmoore , please confirm fix and close.

**Comment by csmoore** [comment]
Verified the "unspecified" entries in symbolset domains, @abouffard - did you want me to close this issue or are you using this issue to also track the administrative updates to those text modifier figures/tables in the standard?

**Comment by abouffard** [comment]
Don't close it yet.  I'll draft a CP we can track then I'll close this.

**Comment by abouffard** [comment]
It was determined by the SSMC that this does not require a CP and any corrections to the standard to address the issue described herein can be handled by an administrative change.  I will work with @mepler to identify any administrative changes that need to be made.  Closing on the basis that no CP will be written for this.  DISA is aware that this needs to be looked at from an administrative standpoint.

**Comment by csmoore** [comment]
Closing this is fine-as long as it is being tracked to closure somewhere with the other admin issues. Also, if this is a valid field, please add to the missing database fields at https://github.com/Esri/military-features-data/issues/141
