### ISSUE TITLE
Add Readme Section for "Projects using the repo"

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#206]
I saw where @joebayles added this [project link](https://github.com/Esri/joint-military-symbology-xml/commit/87dfa03873e931a0d00755ab4fa6475e32809c11), which was a great app/project reference.
 
But perhaps we can now add a new Readme Section ex. "Projects using the repo" to showcase all the projects using this data, here are the ones I know about (but please add any others you may know about):

1. ArcGIS Pro/Runtime/Server - https://github.com/Esri/military-features-data 
2. http://kjellmf.github.io/military-symbology-explorer - https://github.com/kjellmf/military-symbology-explorer (the one Joe mentions)
3. http://spatialillusions.com/milsymbol/docs/milsymbol-2525d.html - https://github.com/spatialillusions/milsymbol

It would be good to include both the live/product link and github repo for each where available.

**Comment by joebayles** [comment]
:+1:

**Comment by joebayles** [comment]
https://github.com/Esri/joint-military-symbology-xml/pull/226

**Comment by csmoore** [comment]
Still awaiting merge - assigning to @abouffard to verify

**Comment by joebayles** [comment]
Verified.
