### ISSUE TITLE
Treat redundant lines and areas like redundant points?

### ISSUE THREAD

**Issue by joebayles** [Esri/joint-military-symbology-xml#219]
In the spirit of reducing redundancy in the standard and the strain on implementers; since most of these lines and areas are the same, why don't we have more generic line and area graphics?

![image](https://cloud.githubusercontent.com/assets/5016557/9739991/51e2ab40-5607-11e5-8988-01891f7db624.png)

The actual base graphic used for several of these lines and areas is identical, and it's only the label that changes, for instance:

![image](https://cloud.githubusercontent.com/assets/5016557/9740230/71e97a08-5608-11e5-9754-08cd016eed0c.png)

The only difference between these is the E, L, or P. Everything else is the same. There is talk about doing this for control measure points, but not lines or areas, as far as I know.

**Comment by abouffard** [comment]
@ottenw, you were working on the reorganization of Appendix H and, in so doing, the simplification of these types of redundancies.  Please take note of @joebayles recommendation.

Thanks

**Comment by joebayles** [comment]
@ottenw, I completely forgot that you were working on Appendix H. I'm sure in your infinite wisdom that you've accounted for this already.

**Comment by joebayles** [comment]
@ottenw, I can't recall... is this still germane or can we close it?

**Comment by ottenw** [comment]
@joebayles @abouffard  we will have simplified draw rules in Ch1; we should be seeing the draft soon.  It is a great first step but not the desired end state.  There are still issues with standardization and figures H-4, H-5, H-6 and their descriptive text sections.  Time permitting I will draft a CP to fix what I perceive to be issues/problems created by the inclusion of H-4 thru H-6.  For now, I would recommend closing this thread, evaluate Ch1 updates, reassess the issue WRT what has been fixed / improved / changed, and start a new thread if needed.

**Comment by joebayles** [comment]
@ottenw thanks!
Closing for now.
