### ISSUE TITLE
Produce APP-6(B) <-> 2525D/APP-6(D) Conversion Table

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#225]
Similar to the 2525C <-> 2525D legacy conversion/interopability work, we want to support the same thing with APP-6(B) so just want to get the planning for this kicked off and tasked:
- [ ] Determine if a member of the SSMC or support staff or other have produced a legacy mapping table from APP-6(B) similar to [what was produced for 2525C](https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/legacy_support/LegacyMappingTableCtoD.csv)
- [ ] If not, submit a request to get this work initiated
- [ ] Once we have the validated source data to do the conversion, add tasks to enable this repo to support producing tables similar to what is available with 2525C<->D : [Id Mapping Table](https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/legacy_support/All_ID_Mapping_C_to_D.csv) , [Generic mapping table](https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/legacy_support/LegacyMappingTableCtoD.csv)

The expectation/end-goal is a LegacyMappingTableAPP6Bto2525D.csv (example name, name doesn't matter) & All_ID_Mapping_App6B_to_D.csv produced within the "version after next" milestone timeframe

**Comment by csmoore** [comment]
Just looping in @kerryrobinson - since this issue would be a prerequisite to any potential future effort to map legacy APP standards to D.

**Comment by gsl123** [comment]
Is there a mapping table between APP6A-APP6C?

**Comment by joebayles** [comment]
We are currently not able to discuss APP-6, APP-6A, APP-6B, or APP-6C. We have asked NATO to reconsider. If we can at some point, this will be revisited.
