### ISSUE TITLE
 Echelon availability vs Quantity

### ISSUE THREAD

**Issue by meterlongcat** [Esri/joint-military-symbology-xml#236]
Good afternoon,

From what I can tell the availability of amplifier B (Echelon) is not enforced correctly in JMSML as per table VII of MIL-STD-2525D. Table VII shows that amplifier B is valid for Units and Activities. In contrast, amplifier C (Quantity) is valid for Equipment. As an example, consider the following two SIDCs:

10031001111800001212 (Land Unit)
10031501112200000500 (Land Equipment)

The first should display amplifier B, whereas the second shouldn't. Both however do. Interestingly the Echelon graphic for the second touches the symbol frame which is not consistent with Figure D-3 of the spec, although ultimately it shouldn't be displayed at all.

Are you able to verify this? I've had a thorough look through existing issues and change requests, so hope I'm not reporting a known problem.

----------

I came across this while looking at amplifier C and where it should be rendered. Table VII makes it clear that Echelon (B) and Quantity (C) are mutually exclusive across Units and Equipment. I wanted to ask a quick related question that you're probably best positioned to answer given your expertise with 2525 symbology.

Have you ever seen Quantity (numerical amplifier text) displayed at the bottom-right of the symbol frame? Perhaps in older releases of 2525, or other symbology systems? I've been shown a number of symbols where it is displayed there.

I have checked the 2525C and 2525D specs and can find no evidence of support for this. I therefore assume the symbols I saw have deviated from the spec. Finally, figure 13 of MIL-STD-2525C shows amplifier C in action whereas MIL-STD-2525D has done away with this useful graphic.

Kind Regards,
Jan

**Comment by meterlongcat** [comment]
This appears to be related to, but not a duplicate of #113

**Comment by csmoore** [comment]
@jrweakland - I cleared my assignment - this seems to be a standard question for @abouffard (in this case: "why/was that attribute removed in D")

**Comment by jrweakland** [comment]
@csmoore - I assigned this to you because of the reorg on the team. Please reassign as you see fit.

**Comment by csmoore** [comment]
@jrweakland - it is a bit confusing but I think the repo owners are supposed to manage these issues for their repo, but maybe we need to clarify that role/responsibility, and I don't mind trying to answer this question.

@meterlongcat - from helping to put together table/schemas for each symbol set I know it is somewhat confusing which text attributes go with which symbol set (the results of our exercise in doing this is here: https://github.com/Esri/joint-military-symbology-xml/tree/master/samples/military_feature_schemas ) but the overall placement seems to be clear  and we only found a few inconsistencies in going through these tables ( [example](https://github.com/Esri/joint-military-symbology-xml/issues/204) ) - here is the graphic/table from the 2525D standard (in Appendix D) showing this placement (I can't speak for the earlier versions) : 

![image](https://cloud.githubusercontent.com/assets/3090809/11896555/86cd176c-a555-11e5-96dc-4f01a1cf0f39.png)

I'll close this if I don't hear back (or assign to Andy if we do)

**Comment by ottenw** [comment]
The placement hasn't changed much over the years / through the different versions.  See below, version is included in the filenames - MIL-STD-2525B Ch1, Ch2, and MIL-STD-2525C.
![mil-std-2525b ch1 figure 3 field positions for tactical symbols](https://cloud.githubusercontent.com/assets/6909159/11898820/67a13dc2-a560-11e5-81ce-89a2ff21c9cd.JPG)
![mil-std-2525b ch2 figure 3 field positions for tactical symbols](https://cloud.githubusercontent.com/assets/6909159/11898829/738d8294-a560-11e5-9484-f09c0069a7c5.JPG)
![mil-std-2525c figure 2 field positions for tactical symbols](https://cloud.githubusercontent.com/assets/6909159/11898834/7b82cf18-a560-11e5-8ecd-e2ebbfa806f0.JPG)

**Comment by ottenw** [comment]
From top to bottom:
MIL-STD-2525B Ch1 Figure 3
MIL-STD-2525B Ch2 Figure 3
MIL-STD-2525C Figure 2

**Comment by meterlongcat** [comment]
@csmoore @ottenw Thank you for your responses. Based on your images it's clear that Quantity has always been positioned above the symbol frame and never on the bottom-right. I therefore conclude that the images I was shown (which displayed a numerical quantity on the bottom-right corner of the frame) were deviations from the 2525 specs.

The question that still remains unanswered is whether amplifier B should be displayed in the two example SIDCs I listed. My understanding is that it should for the first, but shouldn't for the second. Both SIDCs however show the amplifier.

**Comment by abouffard** [comment]
Yes, Table VII does suggest, by its wording, that Quantity and Echelon are mutually exclusive between Equipment and Units respectively.  The relevant descriptions in table D-II would seem to reinforce that interpretation as well.  I'm sure @ottenw can confirm this as Army doctrine.

JMSML contains a definition of the 2525D codes and their meanings, it doesn't, in general, enforce doctrine, like guidance as to when a user should use an echelon code or when they should not.  It does, however, include the description text for each entry in Table VII, so it does capture the doctrinal information therein.

JMSML's C# sample code parses and draws what it sees with any given SIDC, it doesn't, currently, apply doctrine either, or test to see if a given SIDC violates said doctrine.  

If, for example, your system considers an equipment SIDC with an echelon code a "mistake" and you choose to model the doctrine that says one shouldn't apply an echelon code to an equipment symbol, then you, as an implementer, must decide how to draw that symbol, with or without the echelon amplifier.  Our implementation, for development and test of JMSML, goes ahead and draws it.

**Comment by ottenw** [comment]
I concur with @abouffard - this is doctrine, and I believe it is not limited to the Army; rather, it's more about training and knowledge of the individual creating the report.  For example, an individual could see 20 armored personnel carriers (APCs) lined up on a road and report that they see a quantity of 20 pieces of equipment - Vehicle, Armored, Armored Personnel Carrier (symbol set 15, 120103).  If the individual is close enough to read the vehicle bumper numbers and observes "A 1-16IN", that individual understands that all 20 APCs are assigned to "A" Company, 1st Battalion 16th Infantry Regiment and knowing that a US mechanized infantry company is usually authorized 20 APCs, then they would report a company sized unit - Movement and Maneuver, Infantry, Armored/Mechanized/Tracked (symbol set 10, 121105) , echelon = company.

**Comment by csmoore** [comment]
Sounds like the question has been answered (and then some) - thanks for everyone's input - closing
