### ISSUE TITLE
Implement recent MilitaryOverlay schema changes in jmsml.config

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#238]
After the team reviews the MilitaryOverlay schema on 11/10 & the final changes for 1.2 are made, we want to get whatever changes are necessary made to this repo to persist these (this was discussed [here](https://github.com/Esri/joint-military-symbology-xml/pull/234#issuecomment-153806014) )  

List of differences: https://github.com/Esri/joint-military-symbology-xml/compare/esri-implementation 

that should be captured in this repo - mainly [jmsml.config?](https://github.com/Esri/joint-military-symbology-xml/blob/master/source/JointMilitarySymbologyLibraryCS/jmsml.config)

Here is a graphic depiction of the changes that need to be reconciled between the 2 versions:

![diffs](https://cloud.githubusercontent.com/assets/3090809/11036387/49daf8b8-86c6-11e5-87c2-cd752ee5bbaf.JPG)
![diffs](https://cloud.githubusercontent.com/assets/3090809/11036393/5108d966-86c6-11e5-99e7-efb1351c4cad.JPG)

**Comment by abouffard** [comment]
Done in #242 .  The new Domain and Schema sample CSV files can now be used with the GDB automation GP tools to build a new GDB.  There will still be some minor differences between the JMSML export files and the Esri implementation export files, since the latter do not have the extra fields for supporting Subtype creation in GDB.

@csmoore , please test these new export CSV files and I will address any remaining issues when I return from vacation/holiday.

**Comment by abouffard** [comment]
A GDB built with the GP tools, based on the #242 schema output can be found here: https://esri.box.com/s/g69907ppzeaix10both0az42uggo05dt

**Comment by csmoore** [comment]
@abouffard - just to confirm before I start verifying this - there should be no differences between master and esri-implementation branches of the samples folder?

**Comment by csmoore** [comment]
I looked at this and it is very close, just need to remove those extra quotes from the non-countycode csvs (this was previously requested at https://github.com/Esri/joint-military-symbology-xml/pull/242#discussion_r47088366 ) since this broke our original contract/convention we agreed upon in early 2015. Assigning back to @abouffard to implement this change before closing,

![image](https://cloud.githubusercontent.com/assets/3090809/11756025/d1323f70-a024-11e5-8337-2d68b07b1cf6.png)

**Comment by abouffard** [comment]
JMSML #248 removes those quotes from all but the actual country codes where embedded commas exist.  So the diff display you have above looks similar to what I have and is correct.

![image](https://cloud.githubusercontent.com/assets/4564846/11758775/f5a7f998-a034-11e5-9afa-757a715e770e.png)

 * Removal of HostileOrEnemy domain
 * Addition of the Schema.ini to help support the domain assignments on subtypes
 * Double quotes removed from all the indicated amplifier CSVs

The military_feature_schemas folders should be identical.

**Comment by csmoore** [comment]
Thanks for the update, looks good (and now behaves more like Excel csv which only adds the quotes if a cell actually has a comma).
