### ISSUE TITLE
Sustainment Area Control Measure Labels?

### ISSUE THREAD

**Issue by joebayles** [Esri/joint-military-symbology-xml#251]
Question for the SSMC/JSP: Should Support Areas have a Unique Designation (T) Label?

Currently, they do not.
![image](https://cloud.githubusercontent.com/assets/5016557/13191350/e916f67e-d717-11e5-8bef-348fc3924d92.png)

All other sustainment areas do. See below:
![image](https://cloud.githubusercontent.com/assets/5016557/13191340/d5e6e79e-d717-11e5-9588-dd0a6cbeec4b.png)

This would affect Regimental, Brigade, and Division Support Areas (25310500-25310700)

**Comment by joebayles** [comment]
@ottenw FYI

**Comment by abouffard** [comment]
Consulted SSMC 16-1.  Result was that Army to research and we'll proceed from there.

**Comment by abouffard** [comment]
Received confirmation from Carlos Soto, USA voting rep to the SSMC.  CASCOM (Mr. Charles Melton) has indicated that BSA are not officially named and do not require an extra field to add name.

@joebayles, suggest we close this.

**Comment by joebayles** [comment]
Closing because the question is answered.
