### ISSUE TITLE
Identify backup/secondary repo owner + update readme

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#259]
Other repos, [example](https://github.com/Esri/solutions-geoprocessing-toolbox/tree/master#repository-owner-matt) - are moving toward having clearly defined primary and secondary/backup repo owners so there are 2 people/POCs available to manage the repo/PRs/Issues(particularly when the primary is out). Defense Solutions is doing this for new repos, but this repo was released before this change.

Determine if this policy applies to this repo, identify the secondary repo owner for this repo, and update the readme to add the primary/secondary repo owners.

**Comment by abouffard** [comment]
Resolved in #319 , naming Joe Bayles and Daniel Barnes as co-secondary repo owners.

**Comment by abouffard** [comment]
@csmoore , please verify and close.  Thank you.

**Comment by csmoore** [comment]
Verified in https://github.com/abouffard/joint-military-symbology-xml/blob/3ed76cde9cc052478eb7d6938ab925463eb4077f/README.md 

This is slightly different from the usual/preferred format ("Contact" section at end of readme) - but this can be your call.  Example: https://github.com/Esri/military-tools-geoprocessing-toolbox#repository-points-of-contact
