### ISSUE TITLE
Anchor point for Headquarters units

### ISSUE THREAD

**Issue by joebayles** [Esri/joint-military-symbology-xml#261]
According to MIL-STD-2525D (D.5.3.3.2.1):
>The headquarters staff amplifier is a line extending downward from the left side of the frame that identifies units, equipment and installations as headquarters. The headquarters staff amplifier shall extend a distance of one octagon height below the bottom of the frame.

There is no mention of the anchor point of the icon changing to reflect the change in the icon. Should the anchor point remain in the center of the unit icon, or should it change to the "base of the flagpole"?

Figure 1: Non-headquarters unit
![image](https://cloud.githubusercontent.com/assets/5016557/13793170/de6d4184-eab2-11e5-9d00-e078c57ed1e6.png)

Figure 2a: Current implementation, headquarters staff added but no change.
![image](https://cloud.githubusercontent.com/assets/5016557/13793180/e5fcdfd6-eab2-11e5-9d75-cb622d655729.png)

Figure 2b: Proposed implementation, headquarters staff added, anchor point changes.
![image](https://cloud.githubusercontent.com/assets/5016557/13793183/ee716182-eab2-11e5-97b8-5c4b0a898b7a.png)

**Comment by ottenw** [comment]
This issue was identified and rectified at SSMC 2015-2 via SSMC approved "15-028C01-AR Updates and Corrections to Amplifier S and Correction of Reference Errors".  Changes will be included in MIL-STD-2525D Ch1

**Comment by joebayles** [comment]
:+1: 
Thanks @ottenw!

**Comment by joebayles** [comment]
@abouffard should I reopen this and keep it open until changes from CP 15-028C01-AR are incorporated into JMSML?
