### ISSUE TITLE
Key and Decisive Terrain

### ISSUE THREAD

**Issue by joebayles** [Esri/joint-military-symbology-xml#262]
During the Military Decision Making Process, Key and Decisive Terrain needs to be identified. There is no prescribed symbology in MIL-STD-2525D; but doctrinally, they are identified with an encircled K _n_ or D _n_, where _n_ is the numeric designation of that point (i.e. Key Terrain 1, Decisive Terrain 1, etc.). Traditionally, it is purple (to differentiate from the rest of the overlay).
![image](https://cloud.githubusercontent.com/assets/5016557/13796642/2b1c56b6-eac5-11e5-9ce4-8661ee82f629.png)

Suggest these point symbols are added to the Control Measures Symbol Set.

**Comment by joebayles** [comment]
FYI @ottenw

**Comment by abouffard** [comment]
SSMC 16-1 says plausible

**Comment by ottenw** [comment]
FYI @joebayles  @abouffard 
MIL-STD-2525 has a control measure symbol for Decision Point.  Am currently reviewing ATP 2-01.3 / MCRP 2-3A 'Intelligence Preparation of the Battlefield/Battlespace" (DISTRIBUTION RESTRICTION: Approved for public release; distribution is unlimited).  This doctrinal publication uses military symbology extensively, and nearly all I have seen so far is MS2525 compliant.  Other symbology used in this publication could be candidates for CPs - like Key Terrain; see Figure 4-7. Key terrain (natural terrain).  Key Terrain is a circle with the letter "K" and a number.  I have also found that this document depicts Guerilla Units, using the letter "G" in the land unit modifier 2 position; see Figure 5-4.  This is not currently supported in MS2525, I will discuss with Army representative to SSMC after I complete my review of this document.  I am considering starting a discussion with a CW5 I worked with years ago (125D Geospatial Information Technician who works in the Army Geospatial Combat Development organization) to see if he / his organization could validate anything we think should be added and anything else they think is doctrinally supported but missing in MS2525.

**Comment by joebayles** [comment]
![image](https://cloud.githubusercontent.com/assets/5016557/14500543/67116190-0157-11e6-889b-906203551c1b.png)

Good call @ottenw thanks. I definitely agree that working with those elements would make for some fine additions to the standard.

**Comment by ottenw** [comment]
@joebayles So after talking with Army SSMC representative, I'm drafting a CP for a Key Terrain control measure.  In reviewing ATP 2-01.3 / MCRP 2-3A 'Intelligence Preparation of the Battlefield/Battlespace", I couldn't help but notice the absence of color; is there a reason the Ket Terrain symbol you showed above is purple?  If we want non affiliation based color rules for this symbol then we will need a really good reason.
![keyterrainexamples](https://cloud.githubusercontent.com/assets/6909159/14608414/385cbfd2-054b-11e6-8e00-29cd4da42143.JPG)

**Comment by joebayles** [comment]
@ottenw agreed. I think it's shown in black and white here because the picture is black and white. I'll do a little more research to find what standard calls it purple. I know it's a thing because CPOF defaults it to purple, and that's what is taught at AOBC/MCCC.

**Comment by joebayles** [comment]
@ottenw I haven't found any document that points to purple, so disregard. I found one slide from an MCCC deck that uses purple, I think it's available [here](http://www.slideshare.net/tjc3rd/military-decision-making-process-mar-081) on slide 36.

**Comment by ottenw** [comment]
@joebayles I'll check with the gentleman at TCM Mission Command / MCoE that coordinates our symbology/graphics requirements and get his input.  Purple or blue as you found is interesting; purple seems to imply applicability to any affiliation (like green for obstacles) while blue seems to imply friendly.

**Comment by ottenw** [comment]
@joebayles After discussing with Army Symbologist I am drafting CPs for Key Terrain and Land unit sector 2 modifier for Guerilla.  We have until next SSMC to resolve color rule for Key Terrain symbol.

**Comment by ottenw** [comment]
@joebayles in drafting the CP for Key Terrain, a new twist - I went to the joint pub referenced for Key Terrain in the Army/Marine Corps, and although the pictures in the Army/Marine Corps pub all show circular symbols, JP 2-01.3 states"Key terrain is commonly depicted on overlays with a large “K”
within a circle or curve that encloses and follows the contours of the designated terrain".  So do we need two symbols, one circular and one an irregular closed polygon?

**Comment by joebayles** [comment]
So, two questions:
1. Should MIL-STD-2525 reflect service-specific publications, or Joint Publications?
2. Who uses JP 2-01.3 that is drawing military overlays at that level?

Frankly, I think:
1. The question should be asked of the services, and depending on that answer:
2. The CP should be written for MIL-STD-2525 dependent on what the services require or identify as doctrinally correct.
3. A CP may/should be written for JP 2-01.3 to clarify/correct the text if necessary.
4. A CP should be written for service publications to better reflect proper doctrine.

No statement on approved colors for the symbol, but may I direct your attention to Figure II-6 _Land Modified Combined Obstacle Overlay_, and specifically the color and shape of Key Terrain.
![image](https://cloud.githubusercontent.com/assets/5016557/15023846/17213b74-11e7-11e6-8fb7-934e6a9dbf92.png)

It's also interesting to note the other colors in that and other diagrams used throughout this publication.

**Comment by joebayles** [comment]
I think I found why they used purple... because it "pops".
![image](https://cloud.githubusercontent.com/assets/5016557/15263591/5735d2d4-1920-11e6-81f1-7d467a1aa7e5.png)

>FM 34-130, _Intelligence Preparation of the Battlefield_, 08 July 1994

**Comment by ottenw** [comment]
@joebayles thank you - I'll edit the CP and add words that purple should be used citing the reference you found.

**Comment by joebayles** [comment]
@ottenw update on this CP?

**Comment by ottenw** [comment]
16-025-AR "Add Key Terrain Control Measure Symbol" - approved as modified, for inclusion in MIL-STD-2525D(1)

**Comment by joebayles** [comment]
Duplicate of #400
