### ISSUE TITLE
ReadMe.MD may have incorrect SIDC conversion 

### ISSUE THREAD

**Issue by davidbuhler** [Esri/joint-military-symbology-xml#272]
[ReadMe](https://github.com/Esri/joint-military-symbology-xml/blob/master/README.md)

I believe "Convert from new style 20-digit SIDC to new style 15-character SIDC" should be "Convert from new style 20-digit SIDC to old style 15-character SIDC". 

> * A .Net (C#) solution that contains projects with all the code to:
>   * Define all the classes needed to import the XML instance data.
>   * Navigate the aforementioned classes to perform the following functions:
>     * Convert from old style 15-character SIDC to new style 20-digit SIDC.
>     * **Convert from new style 20-digit SIDC to new style 15-character SIDC.**
>   * Test the above functions.

**Comment by joebayles** [comment]
Good catch @davidbuhler, we'll change that. Thanks!

**Comment by joebayles** [comment]
Verified, closing.
