### ISSUE TITLE
Country Codes using STANAG 1059 or GENC?

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#273]
This note says that the country codes are using STANAG 1059
https://github.com/Esri/joint-military-symbology-xml/blob/master/instance/jmsml_D_Base.xml#L908 

But the Readme says GENC: https://github.com/Esri/joint-military-symbology-xml#resources

So just trying to clarify which is correct / which file should be modified (readme or XML note)

**Comment by abouffard** [comment]
@csmoore , the correct standard is GENC.  The text in line 908 was copied from 2525D, from the Activities amplifier table G-II, and this was an error in 2525D.  2525D currently has it correct in table VII in the body of the document.  

![image](https://cloud.githubusercontent.com/assets/4564846/14470076/35639c44-00ad-11e6-8fbd-6796c5884a9c.png)

It has been caught and corrected in the latest draft for 2525D Change 1.

![image](https://cloud.githubusercontent.com/assets/4564846/14470092/424f5150-00ad-11e6-9a53-429ba9d4af77.png)

I have now corrected my local copy of JMSML so this change will be merged with my next PR.

**Comment by csmoore** [comment]
Thanks for the clarification (Hopefully that acronym GENC is also defined/linked to somewhere in the standard since I wouldn't know it or where to find unless I searched specifically for "GENC Country Codes").

Please link/reference this issue when you PR and when can close then.

**Comment by abouffard** [comment]
GENC is referenced on page 2 of 2525D.

Under the heading "2.2.2 Other Government documents, drawings and publications"

**Comment by abouffard** [comment]
Resolved in PR #277.  Closing as a result.
