### ISSUE TITLE
Remove "2525" From All_ID_Mapping_X.Standard Entries

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#282]
To make these comparisons a little more efficient (now that frame queries are no longer unique on this table) - I would like these strings changed in the Standard field to something more succint:

Old -> New
2525C -> C
2525Bc2 -> B2

https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/legacy_support/All_ID_Mapping_Latest.csv 

https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/legacy_support/All_ID_Mapping_Original.csv

**Comment by abouffard** [comment]
Fixed in the dev branch in #300 

@csmoore , please verify and close as appropriate.

**Comment by csmoore** [comment]
Verified in latest style submitted for testing
