### ISSUE TITLE
Multiple entries in for C and Bc2 in "Latest" Mapping table

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#283]
There still appear to be 2525Bc2 frame entries in this (latest/current doctrine) mapping table:

https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/legacy_support/All_ID_Mapping_Latest.csv   (use search to look for "2525Bc2")

@abouffard mentioned a couple weeks ago that these would be removed so just adding an issue to track

**Comment by abouffard** [comment]
Thanks @csmoore , I'll take a look and fix.

**Comment by abouffard** [comment]
@csmoore , you should no longer see Bc2 frames in the latest/current mapping table.  Please verify.

**Comment by csmoore** [comment]
I no longer see Bc2 entries - but I'm not sure how to interpret the "2525C" column entries in this table so they may cause some confusion

**Comment by abouffard** [comment]
Closing as the bc2 frames were removed and verified removed from the latest mapping table,
