### ISSUE TITLE
Research and address and/or fix missing legacy 2525C symbols

### ISSUE THREAD

**Issue by abouffard** [Esri/joint-military-symbology-xml#289]
### Icons/symbols that aren't showing up and should be investigated:

| SIDC | Remarks |
| --- | --- |
| GFGPGAG-------X | Not in 2525D - need new SVG |
| GFGPGLC-------X | Not in 2525D - in 2525D this is two FLOT drawn opposite each other - need new SVG |
| GFGPGPRM------X |  |
| GFGPPN--------X |  |
| GFMPNM--------X |  |
| GFMPOA--------X |  |
| GFMPOAD-------X |  |
| GFMPOAO-------X |  |
| OFIPAC--------- |  |
| WA-DBAFF----A-- |  |
| WA-DIPFF---L--- |  |
| WA-DPXCV---L--- |  |
| WA-DWSTSWA--A-- |  |
| WAS-PHT---P---- |  |
| WAS-WP----P---- |  |
| WAS-WSM-MHP---- |  |
| WAS-WSVE--P---- |  |
| WO-DHHDK--P---- |  |
| WO-DIDID---L--- |  |
| WOS-HDS---P---- |  |
| WOS-HHDMDBP---- |  |
| WOS-HHDMDFP---- |  |

**Comment by joebayles** [comment]
@abouffard can you update this issue?

**Comment by Dbarnes1** [comment]
I believe that these issues have been fixed, but @abouffard should verify.

**Comment by joebayles** [comment]
@abouffard did this get fixed?

**Comment by abouffard** [comment]
I believe I did address them.  Independent verification wouldn't hurt as it has been a while now.

**Comment by Dbarnes1** [comment]
@abouffard I'm able to verify as these Icons are now showing up. (I'm pretty sure this issue was fixed a while ago)
