### ISSUE TITLE
SIGINT entries not exporting to military-all-icons.csv

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/joint-military-symbology-xml#290]
In the latest .stylx file I created, the legacy entities are not appearing, rather they are blank, save for 6 space symbols and 4 air symbols:
![image](https://cloud.githubusercontent.com/assets/13024357/14835278/d13bed4a-0bbd-11e6-8201-39331a0c403b.png)

I converted the files to .emf and the entries appear in JMSML, but they do not appear in the military-all-icons.csv, which leads me to believe that there might be a bug in the export from xml. @abouffard checked it out and that is his tentative diagnosis.

**Comment by abouffard** [comment]
@Dbarnes1 , fixed in #291.

Please verify and rebuild and test the legacy stylx.

**Comment by Dbarnes1** [comment]
@abouffard thanks, I'll test/rebuild once i fix some of the other symbol rendering issues this morning.

**Comment by Dbarnes1** [comment]
@abouffard @csmoore This bug has been fixed:
![image](https://cloud.githubusercontent.com/assets/13024357/14966078/7de55f30-1065-11e6-9d59-6c2a84db4b7f.png)
