### ISSUE TITLE
Branch/Milestone maintenance

### ISSUE THREAD

**Issue by joebayles** [Esri/joint-military-symbology-xml#294]
Per the guidance to the team, we should have a dev branch and a v.next branch.

I'd also suggest we clean up some of the other branches that currently exist but may be old.

Version - Next Milestone is overdue by 6 months.

**Comment by abouffard** [comment]
Thanks.  I'll take care of it.  Since most of our current work is for DCGS-A, which is designed for use with released software, we'll start using the new dev branch for that project.

**Comment by abouffard** [comment]
Branches dev and v.next have been created from the current master.

Changes for DCGS-A (Pro 1.2 and ArcGIS 10.3.1) should go in dev.
Changes for Pro 1.3 and ArcGIS 10.4 should go in v.next

**Comment by csmoore** [comment]
Just a quick note - v.next is optional and was primarily intended to be for actual future (ArcGIS) product dependencies (which I wouldn't anticipate this repo would have - but you may want something similar for Change 1).

Also, if/when you clean up the branches - please leave:
https://github.com/Esri/joint-military-symbology-xml/tree/Esri-implementation-mil2525c
https://github.com/Esri/joint-military-symbology-xml/tree/Esri-implementation-no-subtypes 
Until the source data is capable of producing this output.

**Comment by abouffard** [comment]
Thanks @csmoore.   I think v.next will be used for Change 1 - for "future projects" like that.

**Comment by joebayles** [comment]
We can call v.next or Change 1 _mil-std-2525-d-c1_ or maybe just _2525-d-c1_.
@csmoore I didn't mean those, but the patch-1's and sssmc branch look old/unnecessary.

**Comment by joebayles** [comment]
@abouffard can you update the milestones, please?

**Comment by joebayles** [comment]
Verified.
