### ISSUE TITLE
Font Name appears incorrect - extra single quotes

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#296]
Numerous SVGs appear to have an extra pair of single quotes in the svg font-family element:

font-family="**'**sans-serif**'**"  vs. font-family="sans-serif" (Note: I changed this back after Dan edited)

Example:
```
Legacy\2525C\S-S-CLLL---.svg:	<text transform="matrix(1 0 0 1 224.9824 447)" font-family="'sans-serif'" font-size="140">LL</text>
```

This font-family element did not appear this way in the original SVGs - example: https://raw.githubusercontent.com/Esri/joint-military-symbology-xml/master/svg/MIL_STD_2525D_Symbols/Appendices/Air/01110105.svg

Files affected:
Legacy\2525C\S-S-CLLL--.svg
Legacy\2525C\S-S-CLLLAS.svg
Legacy\2525C\S-S-CLLLAS.svg
Legacy\2525C\S-S-CLLLMI.svg
Legacy\2525C\S-S-CLLLMI.svg
Legacy\2525C\S-S-CLLLSU.svg
Legacy\2525C\S-S-CLLLSU.svg
Legacy\2525C\S-S-CMMA--.svg
Legacy\2525C\S-S-CPSUM-.svg
Legacy\2525C\S-S-CPSUT-.svg
Legacy\2525C\S-S-GG----.svg
Legacy\2525C\S-S-GT----.svg
Legacy\2525C\S-S-GU----.svg
Legacy\2525C\S-S-NH----.svg
Legacy\2525C\S-S-NH----.svg
Legacy\2525C\S-S-NI----.svg
Legacy\2525C\S-S-NS----.svg
Legacy\2525C\S-S-XMC---.svg
Legacy\2525C\S-S-XMF---.svg
Legacy\2525C\S-S-XMO---.svg
Legacy\2525C\S-S-XMP---.svg
Legacy\2525C\S-S-XMR---.svg
Legacy\2525C\S-S-XMTU--.svg
Legacy\2525C\S-U-S1----.svg
Legacy\2525C\S-U-S2----.svg
Legacy\2525C\S-U-S3----.svg
Legacy\2525C\S-U-S4----.svg
Legacy\2525C\S-U-SCA---.svg
Legacy\2525C\S-U-SCA---.svg
Legacy\2525C\S-U-SCB---.svg
Legacy\2525C\S-U-SCB---.svg
Legacy\2525C\S-U-SCG---.svg
Legacy\2525C\S-U-SCG---.svg
Legacy\2525C\S-U-SCM---.svg
Legacy\2525C\S-U-SCM---.svg
Legacy\2525C\S-U-SL----.svg
Legacy\2525C\S-U-SNG---.svg
Legacy\2525C\S-U-SNG---.svg
Legacy\2525C\S-U-SNM---.svg
Legacy\2525C\S-U-SNM---.svg 
Legacy\2525C\S-U-SR-----.svg
Legacy\2525C\S-U-SUM---.svg
Legacy\2525C\S-U-SUM---.svg
Legacy\2525C\S-U-SX----.svg
Legacy\2525C\S-U-SX----.svg

**Comment by Dbarnes1** [comment]
@csmoore I'm tackling this now, thanks for catching it. I think the issue is that there is an extra pair of double quotes, so the correct syntax would be 'sans-serif'

**Comment by csmoore** [comment]
That is correct for **style attributes** (which these are not, they are **stand alone attributes**) - so this is a little more complicated. The correct syntax for the ones I've listed is:

`font-family="sans-serif"`  (element-based - [example of this format](https://raw.githubusercontent.com/Esri/joint-military-symbology-xml/master/svg/MIL_STD_2525D_Symbols/Appendices/Air/01110105.svg) )

(unless you are planning on converting to a style attribute: `style="font-family:'sans-serif'; font-size:65;"` - [example of this format](https://raw.githubusercontent.com/Esri/joint-military-symbology-xml/master/svg/MIL_STD_2525D_Symbols/Legacy/2525C/E-I-F-----.svg) )

**Comment by Dbarnes1** [comment]
Ok, in that case I'll remove the extra single quotes. 

Sorry for the confusion

**Comment by csmoore** [comment]
@Dbarnes1 @abouffard - it looks like these changes were introduced here: https://github.com/Esri/joint-military-symbology-xml/commit/75aec190c581e9350237c5fe2a796e1962e23e82 - so if you are using a replacement script you may need to use a more specific pattern to avoid this case.

**Comment by Dbarnes1** [comment]
@csmoore @abouffard I put these changes in (#298) so one of you can verify when you check out the new stylx I'm building now.

**Comment by joebayles** [comment]
Verified.
