### ISSUE TITLE
Few Legacy SVGs Names/Lengths incorrect

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#297]
A few of these appear to have incorrect name and/or lengths in folder: https://github.com/Esri/joint-military-symbology-xml/tree/master/svg/MIL_STD_2525D_Symbols/Legacy/2525C

Name - Length
S-U-SO---	9
S-U-SR-----	11
WOS-HHDMDBP	11
WOS-HHDMDFP	11

**Comment by abouffard** [comment]
@Dbarnes1 - these may be the cause of some still-missing symbols.  Assigning to you to address/fix.

**Comment by Dbarnes1** [comment]
thanks @abouffard. How many characters should there be on the WOS symbols? I didn't edit/am unfamiliar with those SIDC codes.

**Comment by abouffard** [comment]
I think just 10.  They should all be 10.

**Comment by Dbarnes1** [comment]
@csmoore I'm building the legacy stylx now with changes that are in #298 so you can verify these fixes once I put the stylx up.

**Comment by csmoore** [comment]
I checked the files at: https://github.com/Dbarnes1/joint-military-symbology-xml/tree/master/svg/MIL_STD_2525D_Symbols/Legacy 

And name/SIDC lengths now look correct

**Comment by csmoore** [comment]
One other thing @abouffard @Dbarnes1 if that is also the key "WOS-HHDMDB" you are using in the style ( and it does [appear to be the key here](https://raw.githubusercontent.com/Esri/joint-military-symbology-xml/master/samples/imagefile_name_category_tags/Military-All-Icons.csv) ) that is not consistent with the other METOC keys - so the lookup will fail.

I mentioned this lack of consistency with METOC before ("S" in the key but "D" not in #258) - but this key breaks the pattern in a new way - does this need doc'd in https://github.com/Esri/joint-military-symbology-xml/tree/master/svg/MIL_STD_2525D_Symbols/Legacy ?

**Comment by abouffard** [comment]
Thanks for pointing this out.  I'll review and fix.
