### ISSUE TITLE
Duplicate SIDC (multiple entities with same value) causes generate domains to fail

### ISSUE THREAD

**Issue by BobBooth** [Esri/joint-military-symbology-xml#320]
In: https://github.com/Esri/joint-military-symbology-xml/blob/dev/samples/legacy_support/All_ID_Mapping_Original.csv
S-A-WM----
appears twice.  
Missile (Air Missile),S-A-WM----
Missile (Air Missile) : Missile Status : Launched,S-A-WM---- 
This causes the generate domain process to fail.
arcgisscripting.ExecuteError: ERROR 000980: Domain value S-A-WM---- description Missile (Air Missile) : Missile Status : Launched already exists as description Missile (Air Missile).Failed to execute (TableToDomain).

**Comment by abouffard** [comment]
@BobBooth - problem found and fixed in JMSML.  Will appear in my next PR.  In the meantime, you can hand edit the first occurence to change it to S-A-W-----.  That's what it should be.

**Comment by joebayles** [comment]
Verified.
