### ISSUE TITLE
LegacyMapping table missing many entries

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#324]
While testing the mil2525c_b2 DictionaryRenderer with the setting: (setting, value) => ("legacy_standard_switch", "current") - I noticed many errors/missing entries in the source table [All_ID_Mapping_Latest.csv](https://github.com/Esri/joint-military-symbology-xml/blob/dev/samples/legacy_support/All_ID_Mapping_Latest.csv)

This table should be rechecked against the [legacy truth data](https://github.com/Esri/military-features-data/tree/master/data/mil2525c_b2/test_data/truth_data) to determine the source of these errors and this table should be fixed/regenerated.

Example output/results:

![image](https://cloud.githubusercontent.com/assets/3090809/17182671/4dee2aac-53f2-11e6-999b-51fa7b19df1c.png)

**Comment by joebayles** [comment]
@csmoore @Dbarnes1 is this still an issue?

**Comment by csmoore** [comment]
These look OK - 
![image](https://user-images.githubusercontent.com/3090809/28667675-8994cbb6-729a-11e7-818d-9357ab23bf2c.png)

I did have to make some other manual fixes to lines/areas ( still in this branch: https://github.com/Esri/joint-military-symbology-xml/compare/csm-legacy-icon-fixes-06-2016  ) but the point symbols were all good I believe
