### ISSUE TITLE
Adding alternate symbols for operational conditions on Units

### ISSUE THREAD

**Issue by topowright** [Esri/joint-military-symbology-xml#484]
**Question:** 
Are we supposed to draw the Alternate symbols for operational condition modifiers for tactical symbols on units?

Looking closer at this issue made the question become evident: 
https://github.com/Esri/military-features-data/issues/218

On page  19 of 2525C and  page 32 of 2525D: 
http://www.jcs.mil/Portals/36/Documents/Doctrine/Other_Pubs/ms_2525d.pdf

Currently we are drawing this capability on equipment in our 2525b C2 offering and App6 offering. Wondering if we should not be adding that as an option at the Unit level. Here is a image of what we are doing that could be seen as wrong: 
![image](https://user-images.githubusercontent.com/5488313/36053985-ed9bb954-0da8-11e8-8919-1913e7db01eb.png)

Also the graphics that we have are not drawing the same color as the standard depicts. Is this something that has been updated and we have not updated our symbols or are they using this color all graphics?

FYI @lfunkhouser

**Comment by csmoore** [comment]
Just to add to @topowright 's question. There are several of these alternate/optional settings shown in the standard, it would be helpful if we could go to one place to see them listed and determine if they are mandatory to implement. Here are a few examples that come up often:

1. Show Fill/Frame/Icon/Modifier Settings
2. Fill colors: Dark, Medium, Light
3. Show MEDAL icons (for mines)
4. Show Civilian Fill (purple) 
5. Primary or Alternate Operational Condition Icon (mentioned above)
6. etc.

**Comment by joebayles** [comment]
Agreed @csmoore. I have breached the topic before here, https://github.com/Esri/joint-military-symbology-xml/issues/341, but they weren't ready for new issues at that time. I'll bring it up in April.

**Comment by joebayles** [comment]
@topowright In 2525D Change 1 and APP-6D, operational condition amplifiers are allowed for units and installations. 

@csmoore You might want to make another issue for your questions, but @jeconley and @mbriat have implemented most of that in core at this point.
